services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - mysql

  vite:
    image: node:20-alpine
    container_name: vite
    working_dir: /var/www
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    networks:
      - laravel
    depends_on:
      - app


  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: artisan
    working_dir: /var/www
    entrypoint: [ "php", "artisan" ]
    volumes:
      - ./:/var/www
    networks:
      - laravel

volumes:
  mysql-data:

networks:
  laravel:
